name: build script for Battleship Game	

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build SinkingShips			
        run: make SinkingShips

      - name: upload SinkingShips 
        if: ${{ always() }}

        uses: actions/upload-artifact@v4	
        with:
          name: SinkingShips
          path: ./SinkingShips	
        


