name: build script for Battleship Game	

on:							
  push:
    branches: [ "main", "Connor" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4		

      - name: build SinkingShips			
        run: make SinkingShips

      - name: upload SinkingShips 
        if: ${{ always() }}

        uses: actions/upload-artifact@v4	
        with:
          name: SinkingShips
          path: ./SinkingShips	
      
      - name: build test
        if: ${{ always() }}
        run: make test; ./test <testing.txt >out.txt; gcov test-game.c; gcov test-opponentAI.c
      
      - name: upload game.c.gcov
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: game.c Results			
          path: ./game.c.gcov
      
      - name: upload opponentAI.c.gcov
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: opponentAI.c Results			
          path: ./opponentAI.c.gcov	

      - name: build debug
        run: make debug; ./test_script >test_results.txt
  
      - name: upload Results
        if: ${{ always() }}
  
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results			
          path: ./test_results.txt	
        


